### <font color="brown">Problem Set 8: NumPy</font>

In [76]:
import numpy as np
import re

---

#### Problem 1 

Mean normalization: <br>

Mean normalizing is a common data pre-processing step used in Data Science and Machine learning. <br>Write a function that replaces all nan values to zero in a given array. Then, perform mean normalization i.e. subtract, from all items of each row, the mean value of that row.

In [2]:
# e.g. input array
X = np.array([[5,6,np.nan,7],[1,np.nan,0,5],[-1,5,np.nan,2]])
print(X)

[[ 5.  6. nan  7.]
 [ 1. nan  0.  5.]
 [-1.  5. nan  2.]]


In [9]:
arr = np.arange(1,13).reshape(3,4)
print(arr, '\n')
res = arr.mean(axis=1)
print(res, '\n')
print(res.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[ 2.5  6.5 10.5] 

(3,)


In [11]:
arr - arr.mean(axis=1)


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [17]:
arr - arr.mean(axis=1).reshape(3,1)

array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

In [18]:
arr - arr.mean(axis=1,keepdims=True)

array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

In [24]:
def mean_normalize(X):
    X = np.nan_to_num(X)
    Y = X - X.mean(axis=1, keepdims=True)
    return Y
print(X, '\n')
Y = mean_normalize(X)
print(Y)

[[ 5.  6. nan  7.]
 [ 1. nan  0.  5.]
 [-1.  5. nan  2.]] 

[[ 0.5  1.5 -4.5  2.5]
 [-0.5 -1.5 -1.5  3.5]
 [-2.5  3.5 -1.5  0.5]]


#### Problem 2

Given a 2D NumPy array with n rows and k columns, where the rows are students, and the columns are scores on quizzes (integer, between 0 and 20, inclusive), compute a result NumPy array of size k x 3 with the max, min, and average score on each quiz, and, separately, the average class score on all quizzes combined.

In [25]:
scores = np.random.randint(1,21,(10,5))
scores

array([[ 9,  3,  5, 12,  4],
       [19, 16,  4, 10,  5],
       [14,  2, 10,  3, 11],
       [12, 20, 10, 10, 15],
       [12,  7, 18, 17,  1],
       [10,  3,  2, 12, 15],
       [ 2,  1, 11, 17, 17],
       [19,  5, 16, 17,  1],
       [ 2, 13,  4,  3, 11],
       [18,  5, 19, 20, 12]])

In [63]:
def getStats(scores):
    res = np.empty((scores.shape[1],3))
    res[:,0] = np.max(scores,axis=0)
    res[:,1] = np.min(scores,axis=0)
    res[:,2] = np.average(scores,axis=0)

    return res, np.average(scores)

getStats(scores)

(array([[19. ,  2. , 11.7],
        [20. ,  1. ,  7.5],
        [19. ,  2. ,  9.9],
        [20. ,  3. , 12.1],
        [17. ,  1. ,  9.2]]),
 10.08)

#### Problem 3

Write a function that takes a 2D ndarray and cycles the rows up by 1 so that the first row becomes the last, the last becomes second-to-last, etc. 

In [89]:
arr2d = np.random.randint(1,13,(5,3))
print(arr2d, '\n')

[[11  8 12]
 [ 3 11  6]
 [ 3  1 11]
 [ 1 11  6]
 [12  8  5]] 



In [104]:


def rowcycle(ndarr):
    print('test: ', ndarr.shape[0])
    cycle = list(range(1, ndarr.shape[0])) + [0]
    print(cycle, '\n')
    return ndarr[cycle]

print(rowcycle(arr2d))

test:  5
[1, 2, 3, 4, 0] 

[[ 3 11  6]
 [ 3  1 11]
 [ 1 11  6]
 [12  8  5]
 [11  8 12]]


#### Problem 4

Write a function that takes an ndarray and computes the standard deviation of the values in each row, without using the standard deviation function. It should return an array with these standard deviations. 
See https://www.mathsisfun.com/data/standard-deviation-formulas.html

In [18]:
import numpy as np
arr = np.array([[3,1,-2],[1,8,2],[6,1,5]])
print(arr)
print("================")
mn = np.mean(arr, axis=1)
print(mn)
print("================")
mn = mn.reshape(3,1)
print(mn)
print("================")
arr1 = arr-mn
print(arr1)
print("================")
arr1 = arr1 ** 2
print(arr1)
print("================")
arr1 = arr1.sum(axis=1)
print(arr1)
print("================")
arr1 = arr1/arr.shape[1]
print(arr1)
print("================")
arr1 = np.sqrt(arr1)
print(arr1)

[[ 3  1 -2]
 [ 1  8  2]
 [ 6  1  5]]
[0.66666667 3.66666667 4.        ]
[[0.66666667]
 [3.66666667]
 [4.        ]]
[[ 2.33333333  0.33333333 -2.66666667]
 [-2.66666667  4.33333333 -1.66666667]
 [ 2.         -3.          1.        ]]
[[ 5.44444444  0.11111111  7.11111111]
 [ 7.11111111 18.77777778  2.77777778]
 [ 4.          9.          1.        ]]
[12.66666667 28.66666667 14.        ]
[4.22222222 9.55555556 4.66666667]
[2.05480467 3.09120617 2.1602469 ]


#### Problem 5:

Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10. Get the position (index) of the two largest numbers in each row. From the generated 2D array, replace all values greater than 8 to 10 and less than 6 to 5.

In [58]:
a = np.random.uniform(5,10, size=(5,3))
print(a)

max_pos = np.flip(np.argsort(a, axis=1), axis=1)
print(max_pos, "\n")
max_pos = max_pos[:,:2]
print(max_pos, "\n")

new_arr = np.where(a < 6, 5, np.where(a > 8, 10, a))
print(new_arr)




[[9.87717233 8.23802704 8.90261927]
 [6.99795667 6.81187703 6.40405178]
 [5.66622546 9.24241081 9.86837441]
 [6.26487161 7.36002224 5.39886119]
 [8.50408219 7.89456746 6.69895841]]
[[0 2 1]
 [0 1 2]
 [2 1 0]
 [1 0 2]
 [0 1 2]] 

[[0 2]
 [0 1]
 [2 1]
 [1 0]
 [0 1]] 

[[10.         10.         10.        ]
 [ 6.99795667  6.81187703  6.40405178]
 [ 5.         10.         10.        ]
 [ 6.26487161  7.36002224  5.        ]
 [10.          7.89456746  6.69895841]]


#### Problem 6:

Generate *one-hot encodings* for a list of values (classes). One-hot encoding and its applications are explained in the following resources: 
1. https://en.wikipedia.org/wiki/One-hot
2. https://medium.com/@michaeldelsole/what-is-one-hot-encoding-and-how-to-do-it-f0ae272f1179

Write a function that takes a 1-d List as input and return a 2-d Numpy array where the rows are the one-hot encoding of the classes in the list. Eg: Input: ['cat','camel','dog','cat'] <br>
Output: [[1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0]]

In [61]:
def one_hot_encoding(l):
    arr = np.array(l)
    num_classes = np.unique(arr)
    encoding = np.zeros((arr.shape[0], num_classes.shape[0]))
    for i, k in enumerate(arr):
        encoding[i, k-1] = 1
    return encoding

l = [1,2,0,1,2]
print(one_hot_encoding

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [66]:
new_values= np.array([[np.nan,np.nan,np.nan,0,np.nan,0,np.nan], [np.nan,np.nan,np.nan,0,np.nan,0,np.nan], [np.nan,np.nan,np.nan,0,np.nan,0,np.nan]])
new_result= np.count_nonzero(new_values)
print("Counted nan values:",new_result)

np.sum(np.isnan(new_values),axis=1)



Counted nan values: 15


array([5, 5, 5])

In [73]:
nparr = np.array([1,0,4,5,6,7,8,9])
print(nparr)
res = np.where(nparr%2==1,nparr**2,nparr)
print(np.where(nparr%2==1,nparr**2,nparr))


[1 0 4 5 6 7 8 9]
[ 1  0  4 25  6 49  8 81]


In [78]:
regex = r"[\s]*([\s]*[\S][\s]*)([\s]*[\S][\s]*)[\s]*[\S][\s]*\2[\s]*\1[\s]*"
re.match(regex, 'ab c ba ')

<re.Match object; span=(0, 8), match='ab c ba '>